name: Website Pinger

on:
  schedule:
    - cron: "*/1 * * * *"  # every 1 minute
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping website multiple times
        run: |
          for i in {1..2}
          do
            echo "Ping $i"
            curl -L --max-time 15 https://stox.bedwars.workers.dev
            sleep 30
          done
