name: Website Pinger

on:
  workflow_dispatch:  # manual start

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping continuously every 30 seconds
        run: |
          while true
          do
            echo "Ping $(date)"
            status=$(curl -o /dev/null -s -w "%{http_code}" https://stox.bedwars.workers.dev)
            echo "HTTP status code: $status"
            sleep 10
          done
